version: "3"
services:
    transactions:
        container_name: transactions
        image: transactions
        build:
            .
        ports:
            - 3000:3000
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - '27018:27017'